specVersion: 0.0.1
name: sum-reward
description: ''
repository: ''
schema: ./schema.graphql
network:
  endpoint: wss://polkadot.api.onfinality.io/public-ws
  networkIndexer: https://api.subquery.network/sq/subquery/dictionary-polkadot
dataSources:
  - name: main
    kind: substrate/Runtime
    startBlock: 7000000
    mapping:
      handlers:
        - handler: handleReward
          kind: substrate/EventHandler
          filter:
            module: staking
            method: Rewarded
